# Generated by Django 3.1.1 on 2020-09-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Статья без названия', max_length=50, verbose_name='Название')),
                ('anons', models.CharField(default='Статья без анонса', max_length=250, verbose_name='Анонс')),
                ('full_text', models.TextField(default='Пустая статья', verbose_name='Статья')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
